/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module alu_4bit(A, B, OP, Y, Zero, Carry);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  input [3:0] A;
  input [3:0] B;
  output Carry;
  input [2:0] OP;
  output [3:0] Y;
  output Zero;
  wire carry;
  wire [3:0] result;
  sky130_fd_sc_hd__clkinv_1 _060_ (
    .A(OP[2]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _061_ (
    .A(B[0]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__clkinv_1 _062_ (
    .A(A[3]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__xnor2_1 _063_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__xor2_1 _064_ (
    .A(B[3]),
    .B(A[3]),
    .X(_004_)
  );
  sky130_fd_sc_hd__nand2b_1 _065_ (
    .A_N(B[2]),
    .B(A[2]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__xnor2_1 _066_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__xor2_1 _067_ (
    .A(B[2]),
    .B(A[2]),
    .X(_007_)
  );
  sky130_fd_sc_hd__nand2b_1 _068_ (
    .A_N(B[1]),
    .B(A[1]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xnor2_1 _069_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__o21ai_0 _070_ (
    .A1(_001_),
    .A2(A[0]),
    .B1(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__a21o_1 _071_ (
    .A1(_008_),
    .A2(_010_),
    .B1(_007_),
    .X(_011_)
  );
  sky130_fd_sc_hd__a21oi_1 _072_ (
    .A1(_005_),
    .A2(_011_),
    .B1(_004_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _073_ (
    .A(OP[1]),
    .SLEEP(OP[0]),
    .X(_013_)
  );
  sky130_fd_sc_hd__o21ai_0 _074_ (
    .A1(B[3]),
    .A2(_002_),
    .B1(_013_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xnor2_1 _075_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand3_1 _076_ (
    .A(_006_),
    .B(_009_),
    .C(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand3_1 _077_ (
    .A(OP[0]),
    .B(OP[1]),
    .C(_003_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__o22a_1 _078_ (
    .A1(_012_),
    .A2(_014_),
    .B1(_016_),
    .B2(_017_),
    .X(_018_)
  );
  sky130_fd_sc_hd__a211oi_1 _079_ (
    .A1(OP[2]),
    .A2(OP[0]),
    .B1(OP[1]),
    .C1(_015_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nor2_1 _080_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand3_1 _081_ (
    .A(_000_),
    .B(OP[0]),
    .C(OP[1]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand3b_1 _082_ (
    .A_N(OP[1]),
    .B(OP[0]),
    .C(OP[2]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor2_1 _083_ (
    .A(A[0]),
    .B(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _084_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _085_ (
    .A(_000_),
    .B(_013_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__o22ai_1 _086_ (
    .A1(_020_),
    .A2(_021_),
    .B1(_024_),
    .B2(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor3_1 _087_ (
    .A(_019_),
    .B(_023_),
    .C(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__o21ai_0 _088_ (
    .A1(_000_),
    .A2(_018_),
    .B1(_027_),
    .Y(Y[0])
  );
  sky130_fd_sc_hd__nor2_1 _089_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__or3_1 _090_ (
    .A(_000_),
    .B(OP[0]),
    .C(OP[1]),
    .X(_029_)
  );
  sky130_fd_sc_hd__nand2_1 _091_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__o22ai_1 _092_ (
    .A1(_021_),
    .A2(_028_),
    .B1(_029_),
    .B2(_009_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__o22ai_1 _093_ (
    .A1(A[1]),
    .A2(_022_),
    .B1(_025_),
    .B2(_030_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nor2_1 _094_ (
    .A(_031_),
    .B(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nor3_1 _095_ (
    .A(OP[2]),
    .B(OP[0]),
    .C(OP[1]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__xor2_1 _096_ (
    .A(_009_),
    .B(_024_),
    .X(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _097_ (
    .A(_034_),
    .B(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__or3_1 _098_ (
    .A(_001_),
    .B(A[0]),
    .C(_009_),
    .X(_037_)
  );
  sky130_fd_sc_hd__nor3b_1 _099_ (
    .A(OP[2]),
    .B(OP[1]),
    .C_N(OP[0]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nand3_1 _100_ (
    .A(_010_),
    .B(_037_),
    .C(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand3_1 _101_ (
    .A(_033_),
    .B(_036_),
    .C(_039_),
    .Y(Y[1])
  );
  sky130_fd_sc_hd__nand3_1 _102_ (
    .A(_007_),
    .B(_008_),
    .C(_010_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand3_1 _103_ (
    .A(_011_),
    .B(_038_),
    .C(_040_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o21ai_0 _104_ (
    .A1(_009_),
    .A2(_024_),
    .B1(_030_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__xnor2_1 _105_ (
    .A(_006_),
    .B(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _106_ (
    .A(_034_),
    .B(_043_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor2_1 _107_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _108_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__o22ai_1 _109_ (
    .A1(_006_),
    .A2(_029_),
    .B1(_045_),
    .B2(_021_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__o22ai_1 _110_ (
    .A1(A[2]),
    .A2(_022_),
    .B1(_025_),
    .B2(_046_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor2_1 _111_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand3_1 _112_ (
    .A(_041_),
    .B(_044_),
    .C(_049_),
    .Y(Y[2])
  );
  sky130_fd_sc_hd__nand3_1 _113_ (
    .A(_004_),
    .B(_005_),
    .C(_011_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _114_ (
    .A(_038_),
    .SLEEP(_012_),
    .X(_051_)
  );
  sky130_fd_sc_hd__maj3_1 _115_ (
    .A(B[2]),
    .B(A[2]),
    .C(_042_),
    .X(_052_)
  );
  sky130_fd_sc_hd__xnor2_1 _116_ (
    .A(_003_),
    .B(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _117_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _118_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__o22ai_1 _119_ (
    .A1(_003_),
    .A2(_029_),
    .B1(_054_),
    .B2(_021_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__o22ai_1 _120_ (
    .A1(A[3]),
    .A2(_022_),
    .B1(_025_),
    .B2(_055_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__a211o_1 _121_ (
    .A1(_034_),
    .A2(_053_),
    .B1(_056_),
    .C1(_057_),
    .X(_058_)
  );
  sky130_fd_sc_hd__a21o_1 _122_ (
    .A1(_050_),
    .A2(_051_),
    .B1(_058_),
    .X(Y[3])
  );
  sky130_fd_sc_hd__nor4_1 _123_ (
    .A(Y[0]),
    .B(Y[1]),
    .C(Y[2]),
    .D(Y[3]),
    .Y(Zero)
  );
  sky130_fd_sc_hd__a21oi_1 _124_ (
    .A1(B[3]),
    .A2(A[3]),
    .B1(_052_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor3b_1 _125_ (
    .A(_054_),
    .B(_059_),
    .C_N(_034_),
    .Y(Carry)
  );
  assign carry = Carry;
  assign result = Y;
endmodule
