/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* cells_not_processed =  1  *)
(* src = "rtl/alu_4bit.v:1" *)
module alu_4bit(A, B, OP, Y, Zero, Carry);
  (* src = "rtl/alu_4bit.v:21" *)
  wire [4:0] _000_;
  (* src = "rtl/alu_4bit.v:29" *)
  wire [3:0] _001_;
  wire _002_;
  wire [1:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire [2:0] _008_;
  wire [1:0] _009_;
  wire [3:0] _010_;
  wire [1:0] _011_;
  wire [3:0] _012_;
  wire [1:0] _013_;
  wire [3:0] _014_;
  wire [1:0] _015_;
  wire [3:0] _016_;
  wire [1:0] _017_;
  wire [3:0] _018_;
  wire [1:0] _019_;
  wire [1:0] _020_;
  wire _021_;
  wire _022_;
  wire [3:0] _023_;
  wire [2:0] _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  (* src = "rtl/alu_4bit.v:49" *)
  wire [3:0] _033_;
  (* src = "rtl/alu_4bit.v:45" *)
  wire [3:0] _034_;
  (* src = "rtl/alu_4bit.v:41" *)
  wire [3:0] _035_;
  (* src = "rtl/alu_4bit.v:33" *)
  wire [3:0] _036_;
  (* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:432" *)
  wire [1:0] _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  (* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:432" *)
  wire [31:0] _046_;
  (* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:428" *)
  wire [3:0] _047_;
  (* src = "rtl/alu_4bit.v:25" *)
  wire [3:0] _048_;
  (* src = "rtl/alu_4bit.v:21|<techmap.v>:260|<techmap.v>:203" *)
  wire [4:0] _049_;
  (* src = "rtl/alu_4bit.v:45|<techmap.v>:258" *)
  wire [3:0] _050_;
  (* src = "rtl/alu_4bit.v:45|<techmap.v>:260|<techmap.v>:203" *)
  wire [3:0] _051_;
  (* src = "rtl/alu_4bit.v:45|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3" *)
  wire [3:0] _052_;
  wire [3:0] _053_;
  (* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:445" *)
  wire _054_;
  (* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:445" *)
  wire _055_;
  (* src = "rtl/alu_4bit.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _056_;
  (* src = "rtl/alu_4bit.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _057_;
  (* src = "rtl/alu_4bit.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _058_;
  (* src = "rtl/alu_4bit.v:21|<techmap.v>:260|<techmap.v>:222" *)
  wire _059_;
  (* src = "rtl/alu_4bit.v:21|<techmap.v>:260|<techmap.v>:229" *)
  wire _060_;
  (* src = "rtl/alu_4bit.v:21|<techmap.v>:260|<techmap.v>:221" *)
  wire _061_;
  (* src = "rtl/alu_4bit.v:45|<techmap.v>:260" *)
  wire [3:0] _062_;
  (* src = "rtl/alu_4bit.v:45|<techmap.v>:260|<techmap.v>:221" *)
  wire _063_;
  (* src = "rtl/alu_4bit.v:45|<techmap.v>:260|<techmap.v>:221" *)
  wire _064_;
  (* src = "rtl/alu_4bit.v:45|<techmap.v>:260|<techmap.v>:221" *)
  wire _065_;
  (* src = "rtl/alu_4bit.v:45|<techmap.v>:260|<techmap.v>:222" *)
  wire _066_;
  (* src = "rtl/alu_4bit.v:45|<techmap.v>:260|<techmap.v>:229" *)
  wire _067_;
  (* src = "rtl/alu_4bit.v:45|<techmap.v>:260|<techmap.v>:221" *)
  wire _068_;
  (* src = "rtl/alu_4bit.v:2" *)
  input [3:0] A;
  (* src = "rtl/alu_4bit.v:3" *)
  input [3:0] B;
  (* src = "rtl/alu_4bit.v:7" *)
  output Carry;
  (* src = "rtl/alu_4bit.v:4" *)
  input [2:0] OP;
  (* src = "rtl/alu_4bit.v:5" *)
  output [3:0] Y;
  (* src = "rtl/alu_4bit.v:6" *)
  output Zero;
  (* src = "rtl/alu_4bit.v:10" *)
  wire carry;
  (* src = "rtl/alu_4bit.v:9" *)
  wire [3:0] result;
  assign _003_[0] = _000_[0] |(* src = "rtl/alu_4bit.v:49" *)  _023_[1];
  assign _003_[1] = _023_[2] |(* src = "rtl/alu_4bit.v:49" *)  _023_[3];
  assign _025_ = _003_[0] |(* src = "rtl/alu_4bit.v:49" *)  _003_[1];
  assign _026_ = _004_ |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18" *)  _024_[2];
  assign _027_ = _005_ |(* src = "rtl/alu_4bit.v:44|rtl/alu_4bit.v:18" *)  _024_[2];
  assign _028_ = _006_ |(* src = "rtl/alu_4bit.v:40|rtl/alu_4bit.v:18" *)  _024_[2];
  assign _029_ = _007_ |(* src = "rtl/alu_4bit.v:36|rtl/alu_4bit.v:18" *)  _024_[2];
  assign _004_ = _024_[0] |(* src = "rtl/alu_4bit.v:32|rtl/alu_4bit.v:18" *)  _024_[1];
  assign _030_ = _004_ |(* src = "rtl/alu_4bit.v:32|rtl/alu_4bit.v:18" *)  OP[2];
  assign _005_ = OP[0] |(* src = "rtl/alu_4bit.v:28|rtl/alu_4bit.v:18" *)  _024_[1];
  assign _031_ = _005_ |(* src = "rtl/alu_4bit.v:28|rtl/alu_4bit.v:18" *)  OP[2];
  assign _006_ = _024_[0] |(* src = "rtl/alu_4bit.v:24|rtl/alu_4bit.v:18" *)  OP[1];
  assign _032_ = _006_ |(* src = "rtl/alu_4bit.v:24|rtl/alu_4bit.v:18" *)  OP[2];
  assign _008_[0] = _044_ | _043_;
  assign _008_[1] = _042_ | _041_;
  assign _009_[0] = _008_[0] | _008_[1];
  assign _009_[1] = _008_[2] | _040_;
  assign _002_ = _009_[0] | _009_[1];
  assign _054_ = _002_ |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:445" *)  _045_;
  assign _010_[1] = _046_[11] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _046_[15];
  assign _010_[2] = _046_[19] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _046_[23];
  assign _010_[3] = _046_[27] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _046_[31];
  assign _011_[1] = _010_[2] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _010_[3];
  assign _047_[3] = _010_[1] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _011_[1];
  assign _012_[1] = _046_[10] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _046_[14];
  assign _012_[2] = _046_[18] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _046_[22];
  assign _012_[3] = _046_[26] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _046_[30];
  assign _013_[1] = _012_[2] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _012_[3];
  assign _047_[2] = _012_[1] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _013_[1];
  assign _014_[1] = _046_[9] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _046_[13];
  assign _014_[2] = _046_[17] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _046_[21];
  assign _014_[3] = _046_[25] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _046_[29];
  assign _015_[1] = _014_[2] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _014_[3];
  assign _047_[1] = _014_[1] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _015_[1];
  assign _016_[0] = _046_[0] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _046_[4];
  assign _016_[1] = _046_[8] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _046_[12];
  assign _016_[2] = _046_[16] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _046_[20];
  assign _016_[3] = _046_[24] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _046_[28];
  assign _017_[0] = _016_[0] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _016_[1];
  assign _017_[1] = _016_[2] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _016_[3];
  assign _047_[0] = _017_[0] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:441" *)  _017_[1];
  assign _008_[2] = _038_ |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:445" *)  _039_;
  assign _018_[1] = _040_ |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:445" *)  _041_;
  assign _018_[2] = _042_ |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:445" *)  _043_;
  assign _018_[3] = _044_ |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:445" *)  _045_;
  assign _019_[0] = _008_[2] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:445" *)  _018_[1];
  assign _019_[1] = _018_[2] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:445" *)  _018_[3];
  assign _055_ = _019_[0] |(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:445" *)  _019_[1];
  assign _020_[0] = result[0] |(* src = "rtl/alu_4bit.v:57" *)  result[1];
  assign _020_[1] = result[2] |(* src = "rtl/alu_4bit.v:57" *)  result[3];
  assign _021_ = _020_[0] |(* src = "rtl/alu_4bit.v:57" *)  _020_[1];
  assign _007_ = OP[0] |(* src = "rtl/alu_4bit.v:20|rtl/alu_4bit.v:18" *)  OP[1];
  assign _022_ = _007_ |(* src = "rtl/alu_4bit.v:20|rtl/alu_4bit.v:18" *)  OP[2];
  assign _033_[0] = ~(* src = "rtl/alu_4bit.v:49" *) _025_;
  assign Zero = ~(* src = "rtl/alu_4bit.v:57" *) _021_;
  assign _038_ = ~(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18" *) _026_;
  assign _039_ = ~(* src = "rtl/alu_4bit.v:44|rtl/alu_4bit.v:18" *) _027_;
  assign _040_ = ~(* src = "rtl/alu_4bit.v:40|rtl/alu_4bit.v:18" *) _028_;
  assign _041_ = ~(* src = "rtl/alu_4bit.v:36|rtl/alu_4bit.v:18" *) _029_;
  assign _042_ = ~(* src = "rtl/alu_4bit.v:32|rtl/alu_4bit.v:18" *) _030_;
  assign _043_ = ~(* src = "rtl/alu_4bit.v:28|rtl/alu_4bit.v:18" *) _031_;
  assign _044_ = ~(* src = "rtl/alu_4bit.v:24|rtl/alu_4bit.v:18" *) _032_;
  assign _045_ = ~(* src = "rtl/alu_4bit.v:20|rtl/alu_4bit.v:18" *) _022_;
  assign Carry = _054_ ? (* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:445" *) _037_[1] : 1'hx;
  assign result[0] = _055_ ? (* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:445" *) _047_[0] : 1'hx;
  assign result[1] = _055_ ? (* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:445" *) _047_[1] : 1'hx;
  assign result[2] = _055_ ? (* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:445" *) _047_[2] : 1'hx;
  assign result[3] = _055_ ? (* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:445" *) _047_[3] : 1'hx;
  assign _034_[0] = ~(* src = "rtl/alu_4bit.v:45" *) _051_[3];
  assign _050_[1] = ~(* src = "rtl/alu_4bit.v:21|<techmap.v>:258" *) B[1];
  assign _050_[0] = ~(* src = "rtl/alu_4bit.v:25|<techmap.v>:258" *) B[0];
  assign _050_[2] = ~(* src = "rtl/alu_4bit.v:45|<techmap.v>:258" *) B[2];
  assign _050_[3] = ~(* src = "rtl/alu_4bit.v:45|<techmap.v>:258" *) B[3];
  assign _035_[0] = ~(* src = "rtl/alu_4bit.v:41" *) A[0];
  assign _035_[1] = ~(* src = "rtl/alu_4bit.v:41" *) A[1];
  assign _035_[2] = ~(* src = "rtl/alu_4bit.v:41" *) A[2];
  assign _035_[3] = ~(* src = "rtl/alu_4bit.v:41" *) A[3];
  assign _024_[2] = OP[2] ^(* src = "rtl/alu_4bit.v:36|rtl/alu_4bit.v:18" *)  1'h1;
  assign _024_[1] = OP[1] ^(* src = "rtl/alu_4bit.v:28|rtl/alu_4bit.v:18" *)  1'h1;
  assign _024_[0] = OP[0] ^(* src = "rtl/alu_4bit.v:24|rtl/alu_4bit.v:18" *)  1'h1;
  assign _037_[1] = _000_[4] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _045_;
  assign _046_[20] = _001_[0] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _043_;
  assign _046_[21] = _001_[1] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _043_;
  assign _046_[22] = _001_[2] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _043_;
  assign _046_[23] = _001_[3] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _043_;
  assign _046_[28] = _000_[0] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _045_;
  assign _046_[29] = _000_[1] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _045_;
  assign _046_[30] = _000_[2] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _045_;
  assign _046_[31] = _000_[3] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _045_;
  assign _046_[24] = _048_[0] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _044_;
  assign _046_[25] = _048_[1] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _044_;
  assign _046_[26] = _048_[2] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _044_;
  assign _046_[27] = _048_[3] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _044_;
  assign _046_[16] = _036_[0] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _042_;
  assign _046_[17] = _036_[1] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _042_;
  assign _046_[18] = _036_[2] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _042_;
  assign _046_[19] = _036_[3] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _042_;
  assign _046_[12] = _000_[0] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _041_;
  assign _046_[13] = _023_[1] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _041_;
  assign _046_[14] = _023_[2] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _041_;
  assign _046_[15] = _023_[3] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _041_;
  assign _046_[8] = _035_[0] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _040_;
  assign _046_[9] = _035_[1] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _040_;
  assign _046_[10] = _035_[2] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _040_;
  assign _046_[11] = _035_[3] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _040_;
  assign _046_[4] = _034_[0] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _039_;
  assign _046_[0] = _033_[0] &(* src = "rtl/alu_4bit.v:48|rtl/alu_4bit.v:18|<techmap.v>:434" *)  _038_;
  assign _001_[0] = A[0] &(* src = "rtl/alu_4bit.v:21|<techmap.v>:260" *)  B[0];
  assign _001_[1] = A[1] &(* src = "rtl/alu_4bit.v:21|<techmap.v>:260" *)  B[1];
  assign _001_[2] = A[2] &(* src = "rtl/alu_4bit.v:21|<techmap.v>:260" *)  B[2];
  assign _001_[3] = A[3] &(* src = "rtl/alu_4bit.v:21|<techmap.v>:260" *)  B[3];
  assign _000_[1] = _023_[1] ^(* src = "rtl/alu_4bit.v:21|<techmap.v>:263" *)  _001_[0];
  assign _000_[2] = _023_[2] ^(* src = "rtl/alu_4bit.v:21|<techmap.v>:263" *)  _049_[1];
  assign _000_[3] = _023_[3] ^(* src = "rtl/alu_4bit.v:21|<techmap.v>:263" *)  _049_[2];
  assign _000_[0] = A[0] ^(* src = "rtl/alu_4bit.v:21|<techmap.v>:262" *)  B[0];
  assign _023_[1] = A[1] ^(* src = "rtl/alu_4bit.v:21|<techmap.v>:262" *)  B[1];
  assign _023_[2] = A[2] ^(* src = "rtl/alu_4bit.v:21|<techmap.v>:262" *)  B[2];
  assign _023_[3] = A[3] ^(* src = "rtl/alu_4bit.v:21|<techmap.v>:262" *)  B[3];
  assign _048_[3] = _053_[3] ^(* src = "rtl/alu_4bit.v:25|<techmap.v>:263" *)  _051_[2];
  assign _052_[0] = A[0] ^(* src = "rtl/alu_4bit.v:25|<techmap.v>:262" *)  _050_[0];
  assign _053_[1] = A[1] ^(* src = "rtl/alu_4bit.v:25|<techmap.v>:262" *)  _050_[1];
  assign _053_[2] = A[2] ^(* src = "rtl/alu_4bit.v:25|<techmap.v>:262" *)  _050_[2];
  assign _062_[0] = A[0] &(* src = "rtl/alu_4bit.v:45|<techmap.v>:260" *)  _050_[0];
  assign _062_[1] = A[1] &(* src = "rtl/alu_4bit.v:45|<techmap.v>:260" *)  _050_[1];
  assign _062_[2] = A[2] &(* src = "rtl/alu_4bit.v:45|<techmap.v>:260" *)  _050_[2];
  assign _062_[3] = A[3] &(* src = "rtl/alu_4bit.v:45|<techmap.v>:260" *)  _050_[3];
  assign _048_[0] = _052_[0] ^(* src = "rtl/alu_4bit.v:45|<techmap.v>:263" *)  1'h1;
  assign _048_[1] = _053_[1] ^(* src = "rtl/alu_4bit.v:45|<techmap.v>:263" *)  _051_[0];
  assign _048_[2] = _053_[2] ^(* src = "rtl/alu_4bit.v:45|<techmap.v>:263" *)  _051_[1];
  assign _053_[3] = A[3] ^(* src = "rtl/alu_4bit.v:45|<techmap.v>:262" *)  _050_[3];
  assign _056_ = _023_[1] &(* src = "rtl/alu_4bit.v:21|<techmap.v>:260|<techmap.v>:221" *)  _001_[0];
  assign _057_ = _023_[3] &(* src = "rtl/alu_4bit.v:21|<techmap.v>:260|<techmap.v>:221" *)  _001_[2];
  assign _058_ = _059_ &(* src = "rtl/alu_4bit.v:21|<techmap.v>:260|<techmap.v>:221" *)  _049_[1];
  assign _059_ = _023_[3] &(* src = "rtl/alu_4bit.v:21|<techmap.v>:260|<techmap.v>:222" *)  _023_[2];
  assign _060_ = _023_[2] &(* src = "rtl/alu_4bit.v:21|<techmap.v>:260|<techmap.v>:229" *)  _049_[1];
  assign _049_[1] = _001_[1] |(* src = "rtl/alu_4bit.v:21|<techmap.v>:260|<techmap.v>:221" *)  _056_;
  assign _061_ = _001_[3] |(* src = "rtl/alu_4bit.v:21|<techmap.v>:260|<techmap.v>:221" *)  _057_;
  assign _000_[4] = _061_ |(* src = "rtl/alu_4bit.v:21|<techmap.v>:260|<techmap.v>:221" *)  _058_;
  assign _049_[2] = _001_[2] |(* src = "rtl/alu_4bit.v:21|<techmap.v>:260|<techmap.v>:229" *)  _060_;
  assign _063_ = _053_[1] &(* src = "rtl/alu_4bit.v:25|<techmap.v>:260|<techmap.v>:221" *)  _051_[0];
  assign _065_ = _066_ &(* src = "rtl/alu_4bit.v:25|<techmap.v>:260|<techmap.v>:221" *)  _051_[1];
  assign _066_ = _053_[3] &(* src = "rtl/alu_4bit.v:25|<techmap.v>:260|<techmap.v>:222" *)  _053_[2];
  assign _067_ = _053_[2] &(* src = "rtl/alu_4bit.v:25|<techmap.v>:260|<techmap.v>:229" *)  _051_[1];
  assign _051_[0] = _062_[0] |(* src = "rtl/alu_4bit.v:25|<techmap.v>:260|<techmap.v>:212" *)  _052_[0];
  assign _051_[1] = _062_[1] |(* src = "rtl/alu_4bit.v:25|<techmap.v>:260|<techmap.v>:221" *)  _063_;
  assign _068_ = _062_[3] |(* src = "rtl/alu_4bit.v:25|<techmap.v>:260|<techmap.v>:221" *)  _064_;
  assign _064_ = _053_[3] &(* src = "rtl/alu_4bit.v:45|<techmap.v>:260|<techmap.v>:221" *)  _062_[2];
  assign _051_[3] = _068_ |(* src = "rtl/alu_4bit.v:45|<techmap.v>:260|<techmap.v>:221" *)  _065_;
  assign _051_[2] = _062_[2] |(* src = "rtl/alu_4bit.v:45|<techmap.v>:260|<techmap.v>:229" *)  _067_;
  assign _036_[0] = A[0] |(* src = "rtl/alu_4bit.v:33" *)  B[0];
  assign _036_[1] = A[1] |(* src = "rtl/alu_4bit.v:33" *)  B[1];
  assign _036_[2] = A[2] |(* src = "rtl/alu_4bit.v:33" *)  B[2];
  assign _036_[3] = A[3] |(* src = "rtl/alu_4bit.v:33" *)  B[3];
  assign _011_[0] = _010_[1];
  assign _012_[0] = 1'h0;
  assign _013_[0] = _012_[1];
  assign { _049_[4:3], _049_[0] } = { 1'h0, _000_[4], _001_[0] };
  assign _014_[0] = 1'h0;
  assign _015_[0] = _014_[1];
  assign _037_[0] = 1'h0;
  assign _018_[0] = _008_[2];
  assign _010_[0] = 1'h0;
  assign _023_[0] = _000_[0];
  assign _053_[0] = _052_[0];
  assign { _046_[7:5], _046_[3:1] } = 6'h00;
  assign _033_[3:1] = 3'h0;
  assign _034_[3:1] = 3'h0;
  assign Y = result;
  assign carry = Carry;
endmodule
